name: aha_client
description: Dart client for the AVM Home Automation HTTP Interface + Login.
version: 1.0.0
homepage: https://github.com/Skycoder42/aha-dart

environment:
  sdk: "^3.0.0"

dependencies:
  chopper: ^6.1.4
  color: ^3.0.0
  convert: ^3.1.1
  cryptography: ^2.5.0
  enum_flag: ^1.0.2
  freezed_annotation: ^2.2.0
  http: ^1.0.0
  meta: ^1.9.1
  xml: ^6.3.0
  xml_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.5
  chopper_generator: ^6.0.1
  dart_pre_commit: ^5.1.0+1
  dart_test_tools: ^5.1.1
  freezed: ^2.3.5
  test: ^1.24.3
  xml_serializable: ^2.2.2
