name: aha_client
description: Dart client for the AVM Home Automation HTTP Interface + Login.
version: 1.0.0
homepage: https://github.com/Skycoder42/aha-dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  chopper: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.2
  chopper_generator: ^4.0.1
  lint: ^1.6.0
  test: ^1.16.0

