name: aha_client
description: Dart client for the AVM Home Automation HTTP Interface + Login.
version: 1.0.0
homepage: https://github.com/Skycoder42/aha-dart

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  chopper: ^5.1.0
  color: ^3.0.0
  convert: ^3.1.1
  cryptography: ^2.0.5
  enum_flag: ^1.0.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  meta: ^1.8.0
  xml: ^6.1.0
  xml_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  chopper_generator: ^5.1.0+1
  dart_pre_commit: ^4.0.0
  dart_test_tools: ^4.5.3+1
  freezed: ^2.2.1
  test: ^1.22.0
  xml_serializable: ^2.2.2

dart_pre_commit:
  lib-exports: false
  pull-up-dependencies:
    allowed:
      - xml # flutter
