name: CI/CD

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      unitTestPaths: ""

  # cd:
  #   name: CD
  #   uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
  #   needs:
  #     - ci
  #   with:
  #     buildRunner: true
  #   secrets:
  #     PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
